split: test
datasets:
  - dataset_name: "hotchpotch/msmarco-context-relevance"
    subset: "freq2"
    n_samples: 100
  - dataset_name: "hotchpotch/natural-questions-context-relevance"
    subset: "nodup_freq2"
    n_samples: 100
  - dataset_name: "hotchpotch/gooaq-context-relevance-130k"
    subset: "default"
    n_samples: 100
